export const CATALOG_SQL = {
  schemas: "SELECT USERNAME FROM ALL_USERS ORDER BY USERNAME",
  objectOwners: `SELECT DISTINCT OWNER
FROM ALL_OBJECTS
WHERE SUBOBJECT_NAME IS NULL
ORDER BY OWNER`,
  objects: `SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS, LAST_DDL_TIME
FROM ALL_OBJECTS
WHERE OWNER = :owner
AND SUBOBJECT_NAME IS NULL
AND OBJECT_NAME NOT LIKE 'BIN$%'
AND OBJECT_TYPE IN (
  'TABLE', 'VIEW', 'MATERIALIZED VIEW', 'SEQUENCE', 'INDEX',
  'FUNCTION', 'PROCEDURE', 'TRIGGER', 'PACKAGE', 'PACKAGE BODY',
  'TYPE', 'TYPE BODY', 'SYNONYM', 'DATABASE LINK', 'JOB'
)`,
  constraints: `SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, STATUS, SEARCH_CONDITION_VC, R_OWNER, R_CONSTRAINT_NAME, DELETE_RULE
FROM ALL_CONSTRAINTS
WHERE OWNER = :owner
AND CONSTRAINT_NAME NOT LIKE 'BIN$%'
AND CONSTRAINT_TYPE IN ('P', 'R', 'U', 'C')`,
  constraintsLegacy: `SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, STATUS, SEARCH_CONDITION, R_OWNER, R_CONSTRAINT_NAME, DELETE_RULE
FROM ALL_CONSTRAINTS
WHERE OWNER = :owner
AND CONSTRAINT_NAME NOT LIKE 'BIN$%'
AND CONSTRAINT_TYPE IN ('P', 'R', 'U', 'C')`,
  constraintColumns: `SELECT OWNER, CONSTRAINT_NAME, COLUMN_NAME, POSITION
FROM ALL_CONS_COLUMNS
WHERE OWNER = :owner
ORDER BY CONSTRAINT_NAME, POSITION`,
  columns: `SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID
FROM ALL_TAB_COLUMNS
WHERE OWNER = :owner
ORDER BY TABLE_NAME, COLUMN_ID`,
  tables: `SELECT OWNER, TABLE_NAME, NUM_ROWS, BLOCKS
FROM ALL_TABLES
WHERE OWNER = :owner`,
  partitions: `SELECT TABLE_OWNER, TABLE_NAME, PARTITION_NAME, PARTITION_POSITION, NUM_ROWS, BLOCKS
FROM ALL_TAB_PARTITIONS
WHERE TABLE_OWNER = :owner`,
  segments: `SELECT OWNER, SEGMENT_NAME, SEGMENT_TYPE, BYTES
FROM ALL_SEGMENTS
WHERE OWNER = :owner
AND SEGMENT_TYPE IN (
  'TABLE', 'TABLE PARTITION', 'TABLE SUBPARTITION', 'NESTED TABLE',
  'INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION',
  'LOBSEGMENT', 'LOBINDEX'
)`,
  lobs: `SELECT OWNER, TABLE_NAME, SEGMENT_NAME, INDEX_NAME
FROM ALL_LOBS
WHERE OWNER = :owner`,
  indexes: `SELECT OWNER, INDEX_NAME, TABLE_NAME, UNIQUENESS, STATUS, INDEX_TYPE
FROM ALL_INDEXES
WHERE OWNER = :owner`,
  indexColumns: `SELECT INDEX_OWNER, INDEX_NAME, COLUMN_NAME, COLUMN_POSITION, DESCEND
FROM ALL_IND_COLUMNS
WHERE INDEX_OWNER = :owner
ORDER BY INDEX_NAME, COLUMN_POSITION`,
  sources: `SELECT NAME, TYPE, TEXT FROM ALL_SOURCE
WHERE OWNER = :owner
ORDER BY NAME, TYPE, LINE`,
  schedulerJobs: `SELECT OWNER, JOB_NAME, ENABLED, STATE
FROM ALL_SCHEDULER_JOBS
WHERE OWNER = :owner`,
  dbLinks: `SELECT OWNER, DB_LINK, HOST, USERNAME
FROM ALL_DB_LINKS
WHERE OWNER = :owner`,
  dependencies: `SELECT DISTINCT OWNER, NAME, TYPE, REFERENCED_OWNER, REFERENCED_NAME,
REFERENCED_TYPE, DEPENDENCY_TYPE
FROM ALL_DEPENDENCIES
WHERE OWNER = :owner`,
  ddl: "SELECT DBMS_METADATA.GET_DDL(:objectType, :objectName, :owner) FROM DUAL",
  source: `SELECT TEXT FROM ALL_SOURCE
WHERE OWNER = :owner AND NAME = :objectName AND TYPE = :objectType
ORDER BY LINE`,
  sessionUser: "SELECT USER FROM DUAL",
  version: "SELECT BANNER FROM V$VERSION WHERE BANNER LIKE 'Oracle%'",
  privileges: "SELECT PRIVILEGE FROM SESSION_PRIVS",
} as const;
